#' @title Touch up figure and table captions after using `convert_docx_to_rmd()`
#'
#' @description After using `convert_docx_to_rmd()`, figure and table captions
#' are part of the main text and cross references to them are just text and
#' numbers, making it difficult to integrate these `.Rmd` files in reports:
#' they are not automatically renumbered, these captions cannot be listed,...
#' This function replaces the figure and table descriptions with true captions,
#' and cross references to these figures and tables with dynamic references
#' (that refer to the figure or table label).
#'
#'
#' @details This function expects an input that is generated by
#' `convert_docx_to_rmd()`, with \itemize{
#'   \item  figure captions below the figure and starting with `Figuur `,
#'   then a unique number and finally the description in one paragraph
#'   \item  table captions above the table and starting with `Tabel `,
#'   then a unique number and finally the description in one paragraph
#'   \item figures consisting of one image, not 2 figures near each other
#'   \item cross references having the same label as the figure or table they
#'   refer to, so `Figuur ` or `Tabel ` followed by the unique number written
#'   in exactly the same way
#' }
#' Please check carefully for mistakes after using this function
#'
#' @param from The `.Rmd` file to convert.
#' Can be given as an absolute or relative path.
#' @param to The filename to write the resulting `.Rmd` file.
#' Can be given as an absolute or relative path.
#'
#' @export
#'
add_captions <- function(from, to) {
  text <- readLines(from)
  text_1string <- paste(text, collapse = "\n")
  # replace figure caption
  text_1string <-
    gsub(
      pattern =
        "!\\[[^]]*\\]\\(([^\\)]*)\\)\\{([^\\}]*)\\}\\n\\n\\*?\\*?(Figuur \\d*\\D?\\d*)[.:]?\\*?\\*? (.+?)\\n\\n", #nolint
      replacement = "![\\4 \\\\label{\\3}](\\1){\\2}\n\n", #nolint
      x = text_1string
    )
  # replace figure reference
  text_1string <-
    gsub(
      pattern = "([^label\\{])(Figuur \\d*\\D?\\d*)([^\\}])",
      replacement = "\\1Figuur \\\\ref{\\2}\\3",
      x = text_1string
    )
  # replace figure reference met line ending
  text_1string <-
    gsub(
      pattern = "([^label\\{])(Figuur\\n\\d*\\D?\\d*)([^\\}])",
      replacement = "\\1Figuur\n\\\\ref{\\2}\\3",
      x = text_1string
    )
  # replace table caption of table starting with +--
  text_1string <-
    gsub(
      pattern =
        "\\n\\n\\*?\\*?(Tabel \\d*\\D?\\d*)[.:]?\\*?\\*? (.+?)\\n\\n\\+--",
      replacement = "\n\nTable: \\2\\\\label{\\1}\n\n+--",
      x = text_1string
    )
  # replace table caption of table starting with caption
  text_1string <-
    gsub(
      pattern =
        "\\n\\n\\*?\\*?(Tabel \\d*\\D?\\d*)[.:]?\\*?\\*? (.+?)\\n\\n ?(.+?)\\n ? ?--", #nolint
      replacement = "\n\nTable: \\2\\\\label{\\1}\n\n \\3\n  --",
      x = text_1string
    )
  # replace table reference
  text_1string <-
    gsub(
      pattern = "([^label\\{])(Tabel \\d*\\D?\\d*)([^\\}])",
      replacement = "\\1Tabel \\\\ref{\\2}\\3",
      x = text_1string
    )
  # replace table reference with line ending
  text_1string <-
    gsub(
      pattern = "([^label\\{])(Tabel\\n\\d*\\D?\\d*)([^\\}])",
      replacement = "\\1Tabel\n\\\\ref{\\2}\\3",
      x = text_1string
    )
  text2 <- c(unlist(strsplit(text_1string, split = "\\n")), "")
  writeLines(text2, to)
}
