#' @title Touch up figure and table captions after using `convert_docx_to_rmd()`
#'
#' @description After using `convert_docx_to_rmd()`, figure and table captions
#' are part of the main text and cross references to them are just text and
#' numbers, making it difficult to integrate these `.Rmd` files in reports:
#' they are not automatically renumbered, these captions cannot be listed,...
#' This function replaces the figure and table descriptions with true captions,
#' and cross references to these figures and tables with dynamic references
#' (that refer to the figure or table label).
#'
#'
#' @details This function expects an input that is generated by
#' `convert_docx_to_rmd()`, with \itemize{
#'   \item  figure captions below the figure and starting with `Figuur `
#'   (or other name to be defined in variable `name_figure`),
#'   then a unique number and finally the description in one paragraph
#'   \item  table captions above the table and starting with `Tabel `
#'   (or other name to be defined in variable `name_table`),
#'   then a unique number and finally the description in one paragraph
#'   \item figures consisting of one image, not 2 figures near each other
#'   \item cross references having the same label as the figure or table they
#'   refer to, default `Figuur ` or `Tabel ` followed by the unique number
#'   written in exactly the same way
#' }
#' Please check carefully for mistakes after using this function
#'
#' @param from The `.Rmd` file to convert.
#' Can be given as an absolute or relative path.
#' @param to The filename to write the resulting `.Rmd` file.
#' Can be given as an absolute or relative path.
#' @param name_figure name that is given to figures in captions and cross
#' references (default is `Figuur`)
#' @param name_table name that is given to tables in captions and cross
#' references (default is `Tabel`)
#'
#' @export
#'
add_captions <- function(
  from,
  to,
  name_figure = "Figuur",
  name_table = "Tabel") {

  text <- readLines(from)
  text_1string <- paste(text, collapse = "\n")
  # replace figure caption
  text_1string <-
    gsub(
      pattern =
        sprintf(
          "!\\[[^]]*\\]\\(([^\\)]*)\\)\\{([^\\}]*)\\}\\n\\n\\*?\\*?(%s \\d*\\D?\\d*)[.:]?\\*?\\*? (.+?)\\n\\n", #nolint
          name_figure
        ),
      replacement = "![(#fig:\\3) \\4](\\1){\\2}\n\n", #nolint
      x = text_1string
    )
  # replace figure reference
  text_1string <-
    gsub(
      pattern = sprintf("([^\\#fig\\:])(%s \\d*\\D?\\d*)", name_figure),
      replacement = "\\1Figuur \\\\@ref(fig:\\2)",
      x = text_1string
    )
  # replace figure reference met line ending
  text_1string <-
    gsub(
      pattern = sprintf("([^\\#fig\\:])(%s\\n\\d*\\D?\\d*)", name_figure),
      replacement = "\\1Figuur\n\\\\@ref(fig:\\2)",
      x = text_1string
    )
  # replace table caption of table starting with +--
  text_1string <-
    gsub(
      pattern =
        sprintf(
          "\\n\\n\\*?\\*?(%s \\d*\\D?\\d*)[.:]?\\*?\\*? (.+?)\\n\\n\\+--",
          name_table
        ),
      replacement = "\n\nTable: (#tab:\\1) \\2\n\n+--",
      x = text_1string
    )
  # replace table caption of table starting with caption
  text_1string <-
    gsub(
      pattern =
        sprintf(
          "\\n\\n\\*?\\*?(%s \\d*\\D?\\d*)[.:]?\\*?\\*? (.+?)\\n\\n ?(.+?)\\n ? ?--", #nolint
          name_table
        ),
      replacement = "\n\nTable: (#tab:\\1) \\2\n\n \\3\n  --",
      x = text_1string
    )
  # replace table reference
  text_1string <-
    gsub(
      pattern = sprintf("([^\\#tab\\:])(%s \\d*\\D?\\d*)", name_table),
      replacement = "\\1Tabel \\\\@ref(tab:\\2)",
      x = text_1string
    )
  # replace table reference with line ending
  text_1string <-
    gsub(
      pattern = sprintf("([^\\#tab\\:])(%s\\n\\d*\\D?\\d*)", name_table),
      replacement = "\\1Tabel\n\\\\@ref(tab:\\2)",
      x = text_1string
    )
  text2 <- c(unlist(strsplit(text_1string, split = "\\n")), "")
  writeLines(text2, to)
}
