on:
  push:
    branches-ignore:
      - main
      - master
      - ghpages

name: "check package with checklist"

jobs:
  check-package:
    runs-on: ubuntu-latest
    name: "check package"
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ZENODO_SANDBOX: ${{ secrets.ZENODO_SANDBOX }}
    permissions:
      contents: read
    steps:
      - uses: inbo/actions/check_pkg@main
        with:
          cmd: |
            sudo apt-get install -y pandoc git libcurl4-gnutls-dev libssl-dev make libgit2-dev zlib1g-dev libsecret-1-dev imagemagick libmagick++-dev gsfonts libpng-dev libfreetype6-dev libjpeg-dev libtiff-dev librdf0-dev libsodium-dev libicu-dev libfontconfig1-dev libfribidi-dev libharfbuzz-dev libxml2-dev libuv1-dev
