on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: R-CMD-check-OS

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-22.04,   r: 'devel', rspm: "https://packagemanager.rstudio.com/cran/__linux__/jammy/latest"}
          - {os: ubuntu-22.04,   r: 'oldrel', rspm: "https://packagemanager.rstudio.com/cran/__linux__/jammy/latest"}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      _R_CHECK_SYSTEM_CLOCK_: false
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      ZENODO_SANDBOX: ${{ secrets.ZENODO_SANDBOX }}
      PKG_SYSREQS: false

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          extra-repositories: https://inbo.r-universe.dev

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-tinytex@v2
      - run: tlmgr --version

      - name: Install system dependencies
        if: runner.os == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get -y install pandoc git libcurl4-gnutls-dev libssl-dev make libgit2-dev zlib1g-dev libsecret-1-dev imagemagick libmagick++-dev gsfonts libpng-dev libfreetype6-dev libjpeg-dev libtiff-dev librdf0-dev libsodium-dev libicu-dev libfontconfig1-dev libfribidi-dev libharfbuzz-dev libxml2-dev

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, any::zen4R, any::rlang, any::keyring
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          error-on: '"error"'
